apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "dfclient.labels" . | nindent 4 }}
  name: {{ template "dfclient.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  dfdaemon.yml: |
    {{- toYaml .Values.dfclient.configData | nindent 4}}
    node:
    {{- if not .Values.supernode.statefulSet.enabled }}
      - {{ template "supernode.fullname" . }}:8002
    {{- else }}
      {{- $root := . -}}
      {{- range until (.Values.supernode.replicaCount | int ) }}
      - {{ template "supernode.fullname" $root }}-{{.}}.{{ template "supernode.fullname" $root }}-headless:8002
      {{- end }}
    {{- end }}

